
# Google API
CLIENT_ID = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com'
CLIENT_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXX'
ROW_LIMIT = 25000
GSC_CREDENTIAL_NAME = 'XXXXXXXXXXXXXXXX'

#SEMRush
SEMRUSH_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXX'

# Proxy Service
PROXY_ENDPOINT = 'http://a-proxy-service/endpoint'

RANDOM_SEED = "12345"
